server:
  port: 9000

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/microservice?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
#    url: r2dbc:postgresql://localhost:5432/microservice #?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: your-user-id
    password: your-password
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.r2dbc.core: debug